### PR TITLE
Support absolute length units

### PR DESCRIPTION
**Pull request by gucong3000**
Support absolute length units
- cm
- mm
- pt
- pc
- in

### CODE REVIEW

**Comment by meowsus** [comment]
Hey @gucong3000,

Real-world measurements are a bit beyond the scope of this project. I'm having trouble figuring out why this change would be beneficial to the majority of users of matchmedia since, from a web perspective, we generally measure in pixels.

**Comment by gucong3000** [comment]
We can assume that the screen size is less than 7 inches of the device is a mobile phone, or tablet. with pixels can not make a similar judgment.

**Comment by meowsus** [comment]
This library was intended to be a polyfill for [window.matchMedia](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia), which has pretty great support now. If you're using this project to target mobile devices you may want to use the native browser API instead since the support should be there.

**Pull request closed without merging**
